model_list:
  - model_name: secured-llama
    litellm_params:
      model: openai/meta-llama-3.1-8b-instruct
      api_base: "http://192.168.0.219:1234/v1"
      api_key: "os.environ/LM_STUDIO_AUTH"
      guardrails: ["LlamaProfile"]
      drop_params: true
    model_info:
      supports_function_calling: false

  - model_name: private-llama
    litellm_params:
      model: openai/meta-llama-3.1-8b-instruct
      api_base: "http://192.168.0.219:1234/v1"
      api_key: "os.environ/LM_STUDIO_AUTH"
      drop_params: true
    model_info:
      supports_function_calling: false

guardrails:
  - guardrail_name: "LlamaProfile"
    litellm_params:
      guardrail: "panw_prisma_airs"
      mode: ["pre_call", "post_call"]
      profile_name: "LlamaProfile"
      api_key: "os.environ/PANW_PRISMA_AIRS_API_KEY"
